### ISSUE TITLE
OS Envs that contain equal symbol(s) are mangled when parsed

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-container-go#1]
https://github.com/pip-services3-go/pip-services3-container-go/blob/e68341188bc97fff8ad830fac53fc3d1ee0e0f5e/container/ProcessContainer.go#L133

In the code below, in the event an equal symbol is present within any part (the key or the value) the value will be mangled. I don't think there's a way to handle situations where the key has an equal sign in it (and I agree that it's fairly unlikely) but in the event the value does (i.e. a password) this code will fail further down the line, somewhat inexplicably.

This code seems to solve the problem:
```go
	for _, e := range os.Environ() {
		if env := strings.Split(e, "="); len(env) == 2 {
			parameters.SetAsObject(env[0], env[1])
		} else {
			parameters.SetAsObject(env[0], strings.Join(env[1:], "="))
		}
	}
```

**Comment by levichevdmitry** [comment]
Thanks for reporting!
Fixed in new version, please upgrades to v1.1.5
